# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['d_yates@mail.ru']
#    transport: gmail
#    username:  youmsv@gmail.com
#    password:  0202google.ru.com1990